blank_issues_enabled: false
contact_links:
  - name: cultivars Documentation
    url: https://nikhilxsunder.github.io/cultivars/
    about: Check the documentation for answers to common questions
  - name: GitHub Discussions
    url: https://github.com/nikhilxsunder/cultivars/discussions
    about: Please ask and answer questions here
  - name: Security vulnerabilities
    url: https://github.com/nikhilxsunder/cultivars/blob/main/SECURITY.md
    about: Please report security vulnerabilities as described in our security policy